In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [9]:
df = pd.read_excel("Clientes datos incompletos.xlsx")
df.head()

,ID CLIENTE,CELULAR,E_MAIL,NOMBRE COMPLETO,NOMBRE,APELLIDO
0,1183191,-,CLAUDIA.SCOSS@GMAIL.COM,CLAUDIA DE SOUZA ARAUJO,CLAUDIA DE SOUZA,ARAUJO
1,1770193,-,GARCIAJESUS@GMAIL.COM,JESUS ALEJANDRO GARCIA,JESUS ALEJANDRO,GARCIA
2,5583530,-,GABRIELJDJ@GMAIL.COM,JESUS GABRIEL,JESUS,GABRIEL
3,7464039,-,MANUELEMERCADOP@GMAIL.COM,MANUEL MERCADO,MANUEL,MERCADO
4,10058256,-,FMEJIAG@GMAIL.COM,FERNANDO MEJIA GUTIERRES,FERNANDO,MEJIA GUTIERRES

In [16]:
cedulas = df['ID CLIENTE'].astype(str).tolist()

In [17]:
cedulas_sql = ",".join(f"'{c}'" for c in cedulas)

In [39]:
# 2. Datos de conexión
server = '181.57.189.150,1433'
database = 'Ventas_Shopify'
username = 'sa'
password = 'P@ssw0rd*'

# 3. Codificar usuario y contraseña
encoded_password = quote_plus(password)
encoded_username = quote_plus(username)

# 4. Crear motor de conexión seguro
connection_string = (
    f"mssql+pyodbc://{encoded_username}:{encoded_password}@{server}:1433/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
engine = create_engine(connection_string)

In [61]:
# 5. Consulta
query = f"""
SELECT *
FROM dbo.Cliente
WHERE [Id] IN ({cedulas_sql})
"""

In [62]:
df_resultado = pd.read_sql(query, engine)

In [63]:
df_resultado.head()

,Id,Nombre,Email,Telefono,Direccion,Direccion2,Ciudad,Provincia,Pais,CodigoPostal,Tags
0,1000249982,Sofia Martinez Cañon,sofia.martnez.canon@gmail.com,350 2617314,Transversal 28a 37-35,,Bogota,Bogota,Colombia,11001,
1,1000412158,Maria Jose Bernal Velez,mariajosebernal02@gmail.com,317 5764334,carrera 24 #16AA sur 85,Rincon de San Lucas apto 1014,Medellin,Antioquia,Colombia,05001000,
2,1000472759,Johanna Rozo,rubio.kate@icloud.com,3004350927,Carrera 59 # 22 b 31,Apto 502 torre 1,Bogota,"Bogotá, D.C.",Colombia,11001000,
3,1000604706,ANGELICA RINCON GIL,angelicarincongil@gmail.com,350802620,Calle 12#13-05 frente a notaria 2,Frente a notaria 2 chia papeleria,Chia,Cundinamarca,Colombia,25175000,
4,1000836622,Tania Trujillo,taniavalentina353@gmail.com,3208213228,Cra 3 # 18-32,Edificio ICETEX ?Las aguas,Bogota,"Bogotá, D.C.",Colombia,11001000,| Envío gratis

In [45]:
# 6. Exportar
df_resultado.to_excel('resultado.xlsx', index=False)

In [67]:
df.shape

(5903, 6)