In [246]:
import pandas as pd
from sqlalchemy import create_engine
import urllib
import ast
from datetime import timedelta
import os
from dotenv import load_dotenv

load_dotenv()

True

In [247]:
params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={os.getenv('DB_SERVER')};"
    "DATABASE=Ventas_Comerssia;"
    f"UID={os.getenv('DB_USER')};"
    f"PWD={os.getenv('DB_PASSWORD')};"
)

# Crear el motor de conexión
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [248]:
# query_com = """
# SELECT DISTINCT v.Pedido,
#     c.Cliente,
#     c.Nombres + ' ' + c.Apellidos AS Nombre,
#     c.Email AS Email,
#     c.Celular AS Celular,
#     v.Fecha AS Fecha_Venta,
#     v.Canal,
#     SUM(v.Venta_Neta) AS Venta
# FROM Ventas_Comerssia.dbo.Contacto_Clientes c
# INNER JOIN Ventas_Comerssia.dbo.Ventas_Unificadas v ON c.Cliente = v.Cliente
# WHERE v.fecha >= '2026-04-01'
#     AND v.Fecha <= '2026-04-30'
#     AND v.Venta_Neta > 0
#     AND Descripcion LIKE '%KIT%'
# GROUP BY  v.Pedido,
#     c.Cliente,
#     c.Nombres + ' ' + c.Apellidos,
#     c.Email,
#     c.Celular,
#     v.Fecha,
#     v.Canal
# """

# # Ejecutar y cargar en DataFrame
# df_ventas = pd.read_sql(query_com, engine)

# df_ventas

In [249]:
# CONSULTAS CUMPLEAÑOS

query_data = """
SELECT DISTINCT v.Pedido,
	v.Cliente, 
	cc.Nombres + ' ' +  cc.Apellidos AS Nombre, 
	cc.Email, cc.Celular, 
	v.Fecha AS Fecha_Venta,
    Canal,
    SUM(Venta_Neta) AS Venta
FROM Ventas_Comerssia.dbo.Ventas_Unificadas v
INNER JOIN Ventas_Comerssia.dbo.Contacto_Clientes cc ON cc.Cliente = v.Cliente
WHERE (Codigo_Descuento = '0001 Cumpleaños Cliente 25%' or Codigo_Descuento = 'ABRIL_2026')
	AND Fecha BETWEEN '2026-04-04' AND '2026-04-30'
GROUP BY  v.Pedido,
	v.Cliente,
    cc.Nombres + ' ' +  cc.Apellidos,
    cc.Email,
    cc.Celular,
    v.Fecha,
    v.Canal
"""

# Ejecutar y cargar en DataFrame
df_ventas = pd.read_sql(query_data, engine)
df_ventas.head()

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,4354332112,C20168467,MARIN SALAZAR LUZ,luzmacafe02@hotmail.com,3012748593,2026-04-04,Retail,176470.59
1,4354332120,C22803749,ARIANA MARGARITA SIERRA OSORIO,arianasierraosorio@yahoo.com,3103614120,2026-04-04,Retail,224369.74
2,4354332126,C41445995,AMANDA VICTORIA RODRIGUEZ VALENCIA,amandaro@cable.net.com,3148140262,2026-04-04,Retail,804201.68
3,4354332170,C51724731,VIVIAN PATRICIA PAEZ NIETO,vivianpaez1@gmail.com,3137841648,2026-04-04,Retail,569117.65
4,4354332275,C1015404678,JUANITA LAZARO,juanita2488@yahoo.com,3105617658,2026-04-04,Retail,1389075.63

In [250]:
# Leer archivo
df_indigitall = pd.read_excel("Atribucion.xlsx")

# Seleccionar columnas relevantes
df_campania = df_indigitall[['email', 'campaignName', 'sentAt', 'openedAt', 'clicks']].copy()

# Renombrar columnas
df_campania.rename(columns={
    'email': 'Email',
    'campaignName': 'campania',
    'sentAt': 'fecha_envio',
    'openedAt': 'apertura',
    'clicks': 'clicks'
}, inplace=True)

# 1. Convertir la columna openedAt de string a lista real de fechas
df_campania['apertura'] = df_campania['apertura'].astype(str)
df_campania['apertura'] = df_campania['apertura'].apply(
    lambda x: ast.literal_eval(x) if x.startswith("[") else []
)

# 2. Expandir: cada fecha en una fila
df_expanded = df_campania.explode('apertura').copy()

# 3. Limpiar y convertir a datetime
df_expanded['apertura'] = df_expanded['apertura'].str.strip()
df_expanded['apertura'] = pd.to_datetime(
    df_expanded['apertura'],
    format='%Y-%m-%dT%H:%M:%S.%fZ',
    utc=True,
    errors='coerce'
).dt.date

#Convertir la columna clicks en Fecha
df_campania['clicks'] = df_campania['clicks'].astype(str)

def extraer_fecha_click(valor):
    try:
        # Convertir string a objeto Python (lista de dicts)
        lista = ast.literal_eval(valor)
        if isinstance(lista, list) and len(lista) > 0 and 'clicked_at' in lista[0]:
            fecha = pd.to_datetime(lista[0]['clicked_at'], utc=True, errors='coerce')
            return fecha.date()  # solo fecha
    except Exception:
        return pd.NaT
    return pd.NaT

df_campania['clicks'] = df_campania['clicks'].apply(extraer_fecha_click)

# 4. Normalizar correos
df_expanded['Email'] = df_expanded['Email'].str.lower().str.strip()

# 5. Elegir solo la primera apertura por email
df_abiertos = df_expanded.dropna(subset=['apertura']) \
    .sort_values('apertura') \
    .drop_duplicates(subset='Email', keep='first')

df_clics =  df_campania[df_campania['clicks'].notnull()].copy()

# Filtro correos abiertos hasta una fecha maxima
fecha_maxima = pd.to_datetime('2026-04-30').date()
df_abiertos_filtrados = df_abiertos[df_abiertos['apertura'] <= fecha_maxima]
df_clicks_filtrados = df_clics[df_clics['clicks'] <= fecha_maxima]
total_abiertos = df_abiertos_filtrados['Email'].nunique()
total_clicks = df_clicks_filtrados['Email'].nunique()

In [251]:
# Normalizar df_ventas
df_ventas['Email'] = df_ventas['Email'].str.lower().str.strip()
df_ventas['Fecha_Venta'] = pd.to_datetime(df_ventas['Fecha_Venta']).dt.date

# Merge por email
df_merge = pd.merge(df_ventas, df_abiertos, on='Email', how='inner')

# Filtrar ventas dentro de 5 días desde la apertura
df_merge['dias_post_apertura'] = (df_merge['Fecha_Venta'] - df_merge['apertura']).apply(lambda x: x.days)
df_atribucion = df_merge[
    (df_merge['dias_post_apertura'] >= 0) &
    (df_merge['dias_post_apertura'] <= 5)
]

# Sumar la venta total atribuida
tottal_venta = df_atribucion['Venta'].sum()

filas = len(df_atribucion) # Ver cuántas filas hay realmente

print(f"Número de clientes que abrieron hasta {fecha_maxima}: {total_abiertos}")
print(f"Número de clientes que hicieron clics hasta {fecha_maxima}: {total_clicks}")
print(f"Total de Ventas: {filas}")
print(f"Total de venta atribuida: {tottal_venta:,.2f}"  )
# Resultado final
df_atribucion.head()

Número de clientes que abrieron hasta 2026-04-30: 880
Número de clientes que hicieron clics hasta 2026-04-30: 29
Total de Ventas: 4
Total de venta atribuida: 757,563.02

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,campania,fecha_envio,apertura,clicks,dias_post_apertura
0,4354332503,C52992359,LUISACARRILLO NIVIA CARRILLO,luisa.carrillo@hotmail.com,3182232323,2026-04-04,Retail,111554.62,CUMPLEAÃ‘OS ABRIL,2026-04-04T15:19:06.000Z,2026-04-04,[],0
1,4354332738,C88197793,CIRO LA VERDE,mottilaverde@yahoo.com,3153828681,2026-04-04,Retail,111554.62,CUMPLEAÃ‘OS ABRIL,2026-04-04T15:18:43.000Z,2026-04-04,[],0
2,4354332851,C52388991,MARIA PIEDAD VERGARA,piavergara@gmail.com,3138711434,2026-04-04,Retail,201050.42,CUMPLEAÃ‘OS ABRIL,2026-04-04T15:18:58.000Z,2026-04-04,[],0
3,4354333178,C52154484,SILVANA ESTHER SARMIENTO ROJAS,ester11@hotmail.com,3174253141,2026-04-05,Retail,333403.36,CUMPLEAÃ‘OS ABRIL,2026-04-04T15:19:20.000Z,2026-04-04,[],1

In [252]:
df_atribucion.to_excel('Ventas.xlsx', index=False)