In [415]:
import pandas as pd
from sqlalchemy import create_engine
import urllib
import ast
from datetime import timedelta
import os
from dotenv import load_dotenv

load_dotenv()

True

In [416]:
params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={os.getenv('DB_SERVER')};"
    "DATABASE=Ventas_Comerssia;"
    f"UID={os.getenv('DB_USER')};"
    f"PWD={os.getenv('DB_PASSWORD')};"
)

# Crear el motor de conexión
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [417]:
query_com = """
SELECT DISTINCT Pedido,
    c.Cliente,
    c.Nombres + ' ' + c.Apellidos AS Nombre,
    c.Email AS Email,
    c.Celular AS Celular,
    v.Fecha AS Fecha_Venta,
    v.Canal,
    SUM(v.Venta_Neta) AS Venta
FROM Ventas_Comerssia.dbo.Contacto_Clientes c
INNER JOIN Ventas_Comerssia.dbo.Ventas_Unificadas v ON c.Cliente = v.Cliente
WHERE v.fecha >= '2026-03-02'
    AND v.Fecha <= '2026-03-07'
    AND Ubicacion = 'Social Selling'
    AND v.Venta_Neta > 0
GROUP BY  Pedido,
    c.Cliente,
    c.Nombres + ' ' + c.Apellidos,
    c.Email,
    c.Celular,
    v.Fecha,
    v.Canal
"""

# Ejecutar y cargar en DataFrame
df_ventas = pd.read_sql(query_com, engine)

df_ventas.head()

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,4354281791,C849280,PRAKASH DOWLANI CHANDERSEN,prakos@gmail.com,3152556045,2026-03-02,Chat Center,214285.71
1,4354281853,C52727641,ALEXANDRA LUGO,alexalug@gmail.com,3138956894,2026-03-02,Chat Center,310084.03
2,4354282022,C1015999479,HEIDI LEANDRA ORDOÑEZ RAMOS,printwaves239@gmail.com,3118375864,2026-03-02,Chat Center,2331932.77
3,4354282054,C33358504,YENIR ACEVEDO,yeniracevedo@hotmail.com,3212723220,2026-03-02,Chat Center,136974.79
4,4354282070,C52994267,MARIA ARANGO,crisarango@hotmail.com,3124349962,2026-03-02,Chat Center,1427016.81

In [418]:
# query_com = """
# SELECT DISTINCT Pedido,
#     c.Cliente,
#     c.Nombres + ' ' + c.Apellidos AS Nombre,
#     c.Email AS Email,
#     c.Celular AS Celular,
#     v.Fecha AS Fecha_Venta,
#     v.Canal,
#     SUM(v.Venta_Neta) AS Venta
# FROM Ventas_Comerssia.dbo.Contacto_Clientes c
# INNER JOIN Ventas_Comerssia.dbo.Ventas_Unificadas v ON c.Cliente = v.Cliente
# WHERE v.fecha >= '2026-03-5'
#     AND v.Fecha <= '2026-03-10'
#     AND v.Venta_Neta > 0
# GROUP BY  Pedido,
#     c.Cliente,
#     c.Nombres + ' ' + c.Apellidos,
#     c.Email,
#     c.Celular,
#     v.Fecha,
#     v.Canal
# """

# # Ejecutar y cargar en DataFrame
# df_ventas = pd.read_sql(query_com, engine)

# df_ventas.head()

In [419]:
# # CONSULTAS CUMPLEAÑOS

# # query_data = """
# # SELECT DISTINCT Pedido,
# #     v.Cliente, 
# # 	cc.Nombres + ' ' +  cc.Apellidos AS Nombre, 
# # 	cc.Email, cc.Celular, 
# # 	v.Fecha AS Fecha_Venta,
# # 	Canal,
# #     SUM(Venta_Neta) AS Venta 
# # FROM Ventas_Comerssia.dbo.Ventas_Unificadas v
# # INNER JOIN Ventas_Comerssia.dbo.Contacto_Clientes cc ON cc.Cliente = v.Cliente
# # WHERE (Codigo_Descuento = '0001 Cumpleaños Cliente 25%' or Codigo_Descuento = 'MARZO_2026')
# # 	AND Fecha BETWEEN '2026-03-13' AND '2026-03-18'
# #     AND Canal IN ('Chat Center','CHATCENTER WEB')
# # GROUP BY  Pedido,
# #     v.Cliente,
# #     cc.Nombres + ' ' +  cc.Apellidos,
# #     cc.Email,
# #     cc.Celular,
# #     v.Fecha,
# #     v.Canal
# # """

# query_data = """
# SELECT DISTINCT Pedido,
#     v.Cliente, 
# 	cc.Nombres + ' ' +  cc.Apellidos AS Nombre, 
# 	cc.Email, cc.Celular, 
# 	v.Fecha AS Fecha_Venta,
# 	Canal,
#     SUM(Venta_Neta) AS Venta 
# FROM Ventas_Comerssia.dbo.Ventas_Unificadas v
# INNER JOIN Ventas_Comerssia.dbo.Contacto_Clientes cc ON cc.Cliente = v.Cliente
# WHERE 
# 	Fecha BETWEEN '2026-03-26' AND '2026-03-31'
#     AND Canal IN ('Chat Center','CHATCENTER WEB')
# GROUP BY  Pedido,
#     v.Cliente,
#     cc.Nombres + ' ' +  cc.Apellidos,
#     cc.Email,
#     cc.Celular,
#     v.Fecha,
#     v.Canal
# """


# # Ejecutar y cargar en DataFrame
# df_ventas = pd.read_sql(query_data, engine)
# df_ventas.head()

In [420]:
# Leer archivo
df_social = pd.read_excel("Atribucion.xlsx")

df_social['telefono'] = df_social['telefono'].astype(str).str[2:]

In [421]:
# Normalizar df_ventas
df_ventas['Fecha_Venta'] = pd.to_datetime(df_ventas['Fecha_Venta']).dt.date

# Merge por celular
df_atribucion = pd.merge(df_ventas, df_social, left_on='Celular', right_on='telefono' , how='inner')

# Sumar la venta total atribuida
total_venta = df_atribucion['Venta'].sum()

filas = len(df_atribucion) # Ver cuántas filas hay realmente

print(f"Total de Ventas: {filas}")
print(f"Total de venta atribuida: {total_venta:,.2f}")
# Resultado final
df_atribucion.head()

Total de Ventas: 9
Total de venta atribuida: 3,020,564.00

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,telefono
0,4354282494,C1000556598,PAULINA GUTIERREZ,paulinagutierrez.m18@gmail.com,3152868084,2026-03-02,Chat Center,36470.59,3152868084
1,4354282553,C57430796,MARIA DEL CARMEN GOMEZ,mariadelcgomezf@hotmail.com,3106421111,2026-03-02,Chat Center,1009747.90,3106421111
2,4354283651,C65716591,CLAUDIA PATRICIA HERNANDEZ SALAZAR,chernandezsalazar724@gmail.com,3022839685,2026-03-03,Chat Center,739789.92,3022839685
3,4354285329,C31268705,GLORIA PALMA,mompou21@gmail.com,3155766653,2026-03-05,Chat Center,299285.71,3155766653
4,4354285352,C55224930,MARCELA DEL PILAR PEÑA DIAZ,marcelapde13@hotmail.com,3006094904,2026-03-05,Chat Center,371428.58,3006094904

In [422]:
df_atribucion.to_excel('Ventas.xlsx', index=False)