In [10]:
import pandas as pd
from sqlalchemy import create_engine
import urllib

In [11]:
params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=181.57.189.150,1433;"
    "DATABASE=master;"
    "UID=sa;"
    "PWD=P@ssw0rd*;"
)

# Crear el motor de conexión
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [12]:
query_data = """
SELECT DISTINCT 'C' + c.Id AS Cliente,
       c.Nombre,
       c.Email AS Email,
       c.Telefono AS Celular,
       v.Fecha AS Fecha_Venta,
       v.Canal,
       SUM(v.Valor_Neto) AS Venta
FROM Ventas_Shopify.dbo.Contacto_Clientes c
INNER JOIN Ventas_Shopify.dbo.Ventas_ShopifyMoviNova v ON c.id = v.id_cliente
WHERE v.fecha >= '2025-07-19'
    AND v.Fecha <= '2025-07-19'
    AND Canal != 'MARKETPLACE'
GROUP BY c.Id,
       c.Nombre,
       c.Email,
       c.Telefono,
       v.Fecha,
       v.Canal
"""

# Ejecutar y cargar en DataFrame
ventas_shopify = pd.read_sql(query_data, engine)

query_com = """
SELECT DISTINCT c.CLICodigo AS Cliente,
       c.CLINombres + ' ' + c.CLIApellidos AS Nombre,
       c.CLIEmailPrincipal AS Email,
       c.CLICelular AS Celular,
       v.Fecha AS Fecha_Venta,
       v.Canal,
       SUM(v.Venta_Neta) AS Venta
FROM Ventas_Comerssia.dbo.Contacto_Clientes c
INNER JOIN Ventas_Comerssia.dbo.Ventas_Comerssia v ON c.CLICodigo = v.Cliente
WHERE v.fecha >= '2025-07-19'
    AND v.Fecha <= '2025-07-19'
    AND Canal = 'Chat Center'
GROUP BY  c.CLICodigo,
       c.CLINombres + ' ' + c.CLIApellidos,
       c.CLIEmailPrincipal,
       c.CLICelular,
       v.Fecha,
       v.Canal
"""

# Ejecutar y cargar en DataFrame
ventas_comerssia = pd.read_sql(query_com, engine)

ventas_total = pd.concat([ventas_comerssia, ventas_shopify], ignore_index=True)
ventas_total.head()

,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,C1017196416,LUISA FERNANDA GOMEZ ARANGO,luisagomezar@hotmail.com,3122668619,2025-07-19 00:00:00,Chat Center,158823.53
1,C1020400863,DIANA MARIA LONDOÑO,dianam0927@hotmail.com,3158136416,2025-07-19 00:00:00,Chat Center,141176.47
2,C1020785475,TATIANA LIZARRALDE PUERTO,tatiana.lizarralde@gmail.com,3116803991,2025-07-19 00:00:00,Chat Center,168907.56
3,C1022356215,JOSE RODRIGUEZ BAUTISTA,jose.packvison@gmail.com,3213376631,2025-07-19 00:00:00,Chat Center,289075.63
4,C1037574868,NATALIA RICO GIL,natyricog@hotmail.com,3008243240,2025-07-19 00:00:00,Chat Center,161344.53

In [13]:
# #consulta segmentada 
# query_data = """
# SELECT DISTINCT 'C' + c.Id AS Cliente,
#        c.Nombre,
#        c.Email AS Email,
#        c.Telefono AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(h.Venta_Neta) AS Venta
# FROM Ventas_Shopify.dbo.Contacto_Clientes c
# INNER JOIN Ventas_Shopify.dbo.Ventas_ShopifyMoviNova v ON c.id = v.id_cliente
# INNER JOIN Ventas_Shopify.dbo.Venta_Homologada h ON v.Pedido = h.Pedido
# WHERE v.fecha >= '2025-07-19'
#     AND v.Fecha <= '2025-07-19'
#     AND h.linea = 'ALMENDRA'
#     AND Canal != 'MARKETPLACE'
# GROUP BY c.Id,
#        c.Nombre,
#        c.Email,
#        c.Telefono,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_shopify = pd.read_sql(query_data, engine)

# query_com = """
# SELECT DISTINCT c.CLICodigo AS Cliente,
#        c.CLINombres + ' ' + c.CLIApellidos AS Nombre,
#        c.CLIEmailPrincipal AS Email,
#        c.CLICelular AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(v.Venta_Neta) AS Venta
# FROM Ventas_Comerssia.dbo.Contacto_Clientes c
# INNER JOIN Ventas_Comerssia.dbo.Ventas_Comerssia v ON c.CLICodigo = v.Cliente
# WHERE v.fecha >= '2025-07-19'
#     AND v.Fecha <= '2025-07-19'
#     AND v.linea = 5
#     AND Canal = 'Chat Center'
# GROUP BY  c.CLICodigo,
#        c.CLINombres + ' ' + c.CLIApellidos,
#        c.CLIEmailPrincipal,
#        c.CLICelular,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_comerssia = pd.read_sql(query_com, engine)
# ventas_total = ventas_shopify
# # ventas_total = pd.concat([ventas_comerssia, ventas_shopify], ignore_index=True)
# ventas_total.head()

In [14]:
# # CONSULTAS CUMPLEAÑOS

# query_data = """
# SELECT DISTINCT c.Id AS Cliente,
#        c.Nombre,
#        c.Email AS Email,
#        c.Telefono AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(v.Valor_Neto) AS Venta
# FROM Ventas_Shopify.dbo.Contacto_Clientes c
# INNER JOIN Ventas_Shopify.dbo.Ventas_ShopifyMoviNova v ON c.id = v.id_cliente
# WHERE v.fecha >= '2025-06-06'
#     AND v.Fecha <= '2025-06-30'
#     AND v.Codigo_Descuento LIKE '%CUMP%'
# GROUP BY c.Id,
#        c.Nombre,
#        c.Email,
#        c.Telefono,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_shopify = pd.read_sql(query_data, engine)

# query_com = """
# SELECT DISTINCT c.CLICodigo AS Cliente,
#        c.CLINombres + ' ' + c.CLIApellidos AS Nombre,
#        c.CLIEmailPrincipal AS Email,
#        c.CLICelular AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(v.Venta_Neta) AS Venta
# FROM Ventas_Comerssia.dbo.Contacto_Clientes c
# INNER JOIN Ventas_Comerssia.dbo.Ventas_Comerssia v ON c.CLICodigo = v.Cliente
# WHERE v.Fecha >= '2025-06-06'
#     AND v.Fecha <= '2025-06-30'
#     AND v.ICPDescripcion LIKE '%CUMP%'
# GROUP BY  c.CLICodigo,
#        c.CLINombres + ' ' + c.CLIApellidos,
#        c.CLIEmailPrincipal,
#        c.CLICelular,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_comerssia = pd.read_sql(query_com, engine)

# ventas_total = pd.concat([ventas_comerssia, ventas_shopify], ignore_index=True)
# ventas_total.head()

In [15]:
# Cargar el archivo Excel
df_raw = pd.read_excel("Atribucion.xlsx" )

# Seleccionar columnas relevantes
df_campania = df_raw[['email', 'campaignName', 'sentAt', 'openedAt', 'clicks']].copy()

# Renombrar columnas
df_campania.rename(columns={
    'email': 'Email',
    'campaignName': 'campania',
    'sentAt': 'fecha_envio',
    'openedAt': 'apertura',
    'clicks': 'clics'
}, inplace=True)

# Convertir fecha de envío a formato datetime
df_campania['fecha_envio'] = pd.to_datetime(df_campania['fecha_envio'])

# Extraer primera fecha de apertura (si viene como lista en string)
df_campania['apertura'] = df_campania['apertura'].apply(
    lambda x: eval(x)[0] if isinstance(x, str) and x.startswith('[') and len(eval(x)) > 0 else None
)
df_campania['apertura'] = pd.to_datetime(df_campania['apertura'], errors='coerce').dt.tz_localize(None)
df_campania['fecha_envio'] = pd.to_datetime(df_campania['fecha_envio'], errors='coerce').dt.tz_localize(None)

# Detectar si hubo clics (true si hay al menos un clic registrado en la lista)
def tiene_click(x):
    if isinstance(x, str) and x.startswith('['):
        try:
            return len(eval(x)) > 0
        except:
            return False
    return False

df_campania['clic'] = df_campania['clics'].apply(tiene_click)

# Dejar solo columnas clave para análisis
df_campania = df_campania[['Email', 'campania', 'fecha_envio', 'apertura', 'clic']]

In [16]:
# Filtrar solo clientes que abrieron el correo 

df_abiertos = df_campania[df_campania['apertura'].notnull()].copy()

fecha_maxima = pd.to_datetime('2025-07-19').date()
df_abiertos_filtrados = df_abiertos[df_abiertos['apertura'].dt.date <= fecha_maxima]

df_abiertos_filtrados = df_abiertos_filtrados.drop_duplicates(subset='Email', keep='first')

total_abiertos = df_abiertos_filtrados['Email'].nunique()
print(f"Número de clientes que abrieron hasta {fecha_maxima}: {total_abiertos}")

# Muestra una muestra
df_abiertos_filtrados.head()

Número de clientes que abrieron hasta 2025-07-19: 2776

,Email,campania,fecha_envio,apertura,clic
6,lauramoreno.radio@gmail.com,Almendras sabado 2.0,2025-07-19 13:02:00,2025-07-19 13:03:43,False
19,anaperez75@hotmail.com,Almendras sabado 2.0,2025-07-19 13:02:00,2025-07-19 14:36:52,False
36,cortesbolivar01@gmail.com,Almendras sabado 2.0,2025-07-19 13:00:53,2025-07-19 14:06:32,False
50,amrema98@yahoo.com,Almendras sabado 2.0,2025-07-19 13:01:15,2025-07-19 13:26:16,False
54,didierg52@hotmail.com,Almendras sabado 2.0,2025-07-19 13:01:39,2025-07-19 22:38:28,False

In [17]:
df_abiertos_filtrados['Email'] = df_abiertos['Email'].str.lower()
ventas_total['Email'] = ventas_total['Email'].str.lower()

# Merge entre ventas y campañas abiertas
df_atribucion = pd.merge(
    ventas_total,
    df_abiertos_filtrados[['Email', 'campania', 'apertura']],
    on='Email',
    how='inner'
)

df_atribucion = df_atribucion.drop_duplicates(subset='Email', keep='first')
filas = len(df_atribucion) # Ver cuántas filas hay realmente

# Sumar el total de ventas atribuidas
total_venta = df_atribucion['Venta'].sum()

print(f"Total de venta atribuida: {total_venta:,.0f}")
print(f"Total de filas: {filas}")

df_atribucion.head()

Total de venta atribuida: 7,072,059
Total de filas: 23

,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,campania,apertura
0,C1020734722,Alejandra Vera Cardona,alevc71@gmail.com,3176439081,2025-07-19,Shopify,144957.98,Almendras sabado 2.0,2025-07-19 14:20:23
1,C1045676539,María González,mgm.2088@gmail.com,3043915494,2025-07-19,Shopify,141176.47,Almendras sabado 2.0,2025-07-19 15:00:15
2,C21683915,MARTA MONTOYA,verolopez19@hotmail.com,3122243755,2025-07-19,Shopify,732983.19,Almendras sabado 2.0,2025-07-19 15:54:09
3,C28549291,Andrea Peña,andreapenar@yahoo.com,3222169720,2025-07-19,CHATCENTER WEB,222478.99,Almendras sabado 2.0,2025-07-19 18:26:49
4,C30311641,Luz Maria Gomez,luzmgg2013@gmail.com,3123862094,2025-07-19,Shopify,296848.74,Almendras sabado 2.0,2025-07-19 13:41:23

In [18]:
df_atribucion.to_excel('Ventas.xlsx', index=False)