In [65]:
import pandas as pd
from sqlalchemy import create_engine
import urllib
import ast
from datetime import timedelta
import os
from dotenv import load_dotenv

load_dotenv()

True

In [66]:
params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={os.getenv('DB_SERVER')};"
    "DATABASE=Ventas_Comerssia;"
    f"UID={os.getenv('DB_USER')};"
    f"PWD={os.getenv('DB_PASSWORD')};"
)

# Crear el motor de conexión
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [67]:
query_com = """
SELECT DISTINCT Pedido,
    c.Cliente,
    c.Nombres + ' ' + c.Apellidos AS Nombre,
    c.Email AS Email,
    c.Celular AS Celular,
    v.Fecha AS Fecha_Venta,
    v.Canal,
    SUM(v.Venta_Neta) AS Venta
FROM Ventas_Comerssia.dbo.Contacto_Clientes c
INNER JOIN Ventas_Comerssia.dbo.Ventas_Unificadas v ON c.Cliente = v.Cliente
WHERE v.fecha >= '2026-05-5'
    AND v.Fecha <= '2026-05-10'
    AND Ubicacion = 'Social Selling'
    AND v.Venta_Neta > 0
GROUP BY  Pedido,
    c.Cliente,
    c.Nombres + ' ' + c.Apellidos,
    c.Email,
    c.Celular,
    v.Fecha,
    v.Canal
"""

# Ejecutar y cargar en DataFrame
df_ventas = pd.read_sql(query_com, engine)

df_ventas.head()

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,4354369417,C427700,JORDAN SCHLIPKEN,j.schlipken@aruba.com,3183753407,2026-05-05,Chat Center,642857.13
1,4354369482,C800185150,None,milena.correa@sony.com,3102691387,2026-05-05,Chat Center,957983.16
2,4354369705,C52853176,MARIBEL DIAZ BENITO,maribeldiazbenito@gmail.com,3107724479,2026-05-05,Chat Center,273949.58
3,4354369800,C32702903,FEORELLA SCHEMBRI RIOS,fpschembri@hotmail.com,3173639552,2026-05-05,Chat Center,569117.64
4,4354370162,C1026268896,MANUEL HERRERA,manurherrera234@gmail.com,3175106805,2026-05-06,Chat Center,507142.85

In [ ]:
# CONSULTAS CUMPLEAÑOS

query_data = """
SELECT DISTINCT Pedido,
    v.Cliente, 
	cc.Nombres + ' ' +  cc.Apellidos AS Nombre, 
	cc.Email, cc.Celular, 
	v.Fecha AS Fecha_Venta,
	Canal,
    SUM(Venta_Neta) AS Venta 
FROM Ventas_Comerssia.dbo.Ventas_Unificadas v
INNER JOIN Ventas_Comerssia.dbo.Contacto_Clientes cc ON cc.Cliente = v.Cliente
WHERE (Codigo_Descuento = '0001 Cumpleaños Cliente 25%' or Codigo_Descuento = 'MAYO_2026')
	AND Fecha BETWEEN '2026-05-7' AND '2026-05-12'
    AND Ubicacion IN ('Social Selling')
GROUP BY  Pedido,
    v.Cliente,
    cc.Nombres + ' ' +  cc.Apellidos,
    cc.Email,
    cc.Celular,
    v.Fecha,
    v.Canal
"""


# Ejecutar y cargar en DataFrame
df_ventas = pd.read_sql(query_data, engine)
df_ventas.head()

In [69]:
# Leer archivo
df_social = pd.read_excel("Atribucion.xlsx")

df_social['telefono'] = df_social['telefono'].astype(str).str[2:]

In [70]:
# Normalizar df_ventas
df_ventas['Fecha_Venta'] = pd.to_datetime(df_ventas['Fecha_Venta']).dt.date

# Merge por celular
df_atribucion = pd.merge(df_ventas, df_social, left_on='Celular', right_on='telefono' , how='inner')

# Sumar la venta total atribuida
total_venta = df_atribucion['Venta'].sum()

filas = len(df_atribucion) # Ver cuántas filas hay realmente

print(f"Total de Ventas: {filas}")
print(f"Total de venta atribuida: {total_venta:,.2f}")
# Resultado final
df_atribucion.head()

Total de Ventas: 19
Total de venta atribuida: 5,555,547.84

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,telefono
0,4354369705,C52853176,MARIBEL DIAZ BENITO,maribeldiazbenito@gmail.com,3107724479,2026-05-05,Chat Center,273949.58,3107724479
1,4354369800,C32702903,FEORELLA SCHEMBRI RIOS,fpschembri@hotmail.com,3173639552,2026-05-05,Chat Center,569117.64,3173639552
2,4354370178,C901242489,TEIXPAC LATAM SAS BURCHI,administracion@teixpaclatam.com,3205183763,2026-05-06,Chat Center,710504.20,3205183763
3,4354370184,C1140837756,GISELLA ABDALA,gabdala01@gmail.com,3043887019,2026-05-06,Chat Center,252100.84,3043887019
4,4354370833,C52890126,JOHANNA RODRIGUEZ FACUNDO,johannarodriguezfacundo@gmail.com,3112290565,2026-05-06,Chat Center,325210.08,3112290565

In [71]:
df_atribucion.to_excel('Ventas.xlsx', index=False)