In [13]:
import pandas as pd
from sqlalchemy import create_engine
import urllib
import ast
from datetime import timedelta
import os
from dotenv import load_dotenv

load_dotenv()

True

In [14]:
params = urllib.parse.quote_plus(
    "DRIVER=ODBC Driver 17 for SQL Server;"
    f"SERVER={os.getenv('DB_SERVER')};"
    "DATABASE=Ventas_Comerssia;"
    f"UID={os.getenv('DB_USER')};"
    f"PWD={os.getenv('DB_PASSWORD')};"
)

# Crear el motor de conexión
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [15]:
# query_com = """
# SELECT DISTINCT c.Cliente,
#     c.Nombres + ' ' + c.Apellidos AS Nombre,
#     c.Email AS Email,
#     c.Celular AS Celular,
#     v.Fecha AS Fecha_Venta,
#     v.Canal,
#     SUM(v.Venta_Neta) AS Venta
# FROM Ventas_Comerssia.dbo.View_Contacto_Clientes c
# INNER JOIN Ventas_Comerssia.dbo.Ventas_Unificadas v ON c.Cliente = v.Cliente
# WHERE v.fecha >= '2025-07-19'
#     AND v.Fecha <= '2025-07-19'+
#     AND Canal IN ('Retail','WhatsApp')
#     AND v.Venta_Neta > 0
# GROUP BY  c.Cliente,
#        c.Nombres + ' ' + c.Apellidos,
#        c.Email,
#        c.Celular,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# df_ventas = pd.read_sql(query_com, engine)

# df_ventas.head()

In [16]:
# CONSULTAS CUMPLEAÑOS

query_data = """
SELECT DISTINCT Pedido,
    v.Cliente, 
	cc.Nombres + ' ' +  cc.Apellidos AS Nombre, 
	cc.Email, cc.Celular, 
	v.Fecha AS Fecha_Venta,
	Canal,
    SUM(Venta_Neta) AS Venta 
FROM Ventas_Comerssia.dbo.Ventas_Unificadas v
INNER JOIN Ventas_Comerssia.dbo.Contacto_Clientes cc ON cc.Cliente = v.Cliente
WHERE (Codigo_Descuento = '0001 Cumpleaños Cliente 25%')
	AND Fecha BETWEEN '2026-05-25' AND '2026-05-30'
    AND Canal IN ('Retail', 'WhatsApp')
GROUP BY  Pedido,
    v.Cliente,
    cc.Nombres + ' ' +  cc.Apellidos,
    cc.Email,
    cc.Celular,
    v.Fecha,
    v.Canal
"""


# Ejecutar y cargar en DataFrame
df_ventas = pd.read_sql(query_data, engine)
df_ventas.head()

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,4354398871,C42083485,BEATRIZ OSSA LONDONO,bluedive@hotmail.com,3106574926,2026-05-25,Retail,244537.81
1,4354398937,C37835023,MILADY CELMIRA LOPEZ CARDENAS,miladylopez@hotmail.com,3004946868,2026-05-25,Retail,78151.26
2,4354398944,C43524505,ANGELA MARIA CARDENAS,angela@biancardi.org,3147014267,2026-05-25,Retail,478361.33
3,4354398945,C42878306,LUZ ANGELA VELASQUEZ URIBE,luchivelasquezu@gmail.com,3147710407,2026-05-25,Retail,85084.03
4,4354398956,C43220105,ANA PATRICIA MESA FRANCO,anamesa21@hotmail.com,3146795139,2026-05-25,Retail,302521.00

In [17]:
# Leer archivo
df_social = pd.read_excel("Atribucion.xlsx")

df_social['telefono'] = df_social['telefono'].astype(str).str[2:]

In [18]:
# Normalizar df_ventas
df_ventas['Fecha_Venta'] = pd.to_datetime(df_ventas['Fecha_Venta']).dt.date

# Merge por celular
df_atribucion = pd.merge(df_ventas, df_social, left_on='Celular', right_on='telefono' , how='inner')

# Sumar la venta total atribuida
total_venta = df_atribucion['Venta'].sum()

filas = len(df_atribucion) # Ver cuántas filas hay realmente

print(f"Total de Ventas: {filas}")
print(f"Total de venta atribuida: {total_venta:,.2f}")
# Resultado final
df_atribucion.head()

Total de Ventas: 100
Total de venta atribuida: 58,857,078.36

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,telefono
0,4354398937,C37835023,MILADY CELMIRA LOPEZ CARDENAS,miladylopez@hotmail.com,3004946868,2026-05-25,Retail,78151.26,3004946868
1,4354398944,C43524505,ANGELA MARIA CARDENAS,angela@biancardi.org,3147014267,2026-05-25,Retail,478361.33,3147014267
2,4354398945,C42878306,LUZ ANGELA VELASQUEZ URIBE,luchivelasquezu@gmail.com,3147710407,2026-05-25,Retail,85084.03,3147710407
3,4354398990,C71633516,ADOLFO ESCOBAR,adolfoescobar999@gmail.com,3207746477,2026-05-25,Retail,543277.31,3207746477
4,4354399026,C1020714519,SUSANA LOPEZ,susanalopezgh@hotmail.com,3188275288,2026-05-25,Retail,340336.14,3188275288

In [19]:
df_atribucion.to_excel('Ventas.xlsx', index=False)