In [16]:
import pandas as pd
from sqlalchemy import create_engine
import urllib
import ast
from datetime import timedelta
import os
from dotenv import load_dotenv

load_dotenv()

True

In [17]:
params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={os.getenv('DB_SERVER')};"
    "DATABASE=Ventas_Comerssia;"
    f"UID={os.getenv('DB_USER')};"
    f"PWD={os.getenv('DB_PASSWORD')};"
)


# Crear el motor de conexión
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [18]:
query_com = """
SELECT DISTINCT Pedido,
    c.Cliente,
    c.Nombres + ' ' + c.Apellidos AS Nombre,
    c.Email AS Email,
    c.Celular AS Celular,
    v.Fecha AS Fecha_Venta,
    v.Canal,
    SUM(v.Venta_Neta) AS Venta
FROM Ventas_Comerssia.dbo.Contacto_Clientes c
INNER JOIN Ventas_Comerssia.dbo.Ventas_Unificadas v ON c.Cliente = v.Cliente
WHERE v.fecha >= '2026-03-18'
    AND v.Fecha <= '2026-03-23'
    AND Canal IN ('Shopify')
    AND v.Venta_Neta > 0
GROUP BY  Pedido,
    c.Cliente,
    c.Documento,
    c.Nombres + ' ' + c.Apellidos,
    c.Email,
    c.Celular,
    v.Fecha,
    v.Canal
"""

# Ejecutar y cargar en DataFrame
df_ventas = pd.read_sql(query_com, engine)

df_ventas.head()

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,97144,C43638096,MARIA C JARAMILLO VALLEJO,mcjaramv@yahoo.com.mx,3217180928,2026-03-18,Shopify,129406.20
1,97145,C43878511,MARCELA PÉREZ RAMÍREZ,marcelaperezramirez2882@gmail.com,3114040795,2026-03-18,Shopify,278979.60
2,97149,C91103732,JUAN CARLOS POVEDA,jpovedad@hotmail.com,3214310691,2026-03-18,Shopify,96634.50
3,97150,C36759744,DIANA BASTIDAS,diana.bastidas@gmail.com,3122549695,2026-03-18,Shopify,243771.03
4,97152,C17640437,JAIME NUÑEZ,contabilidad@maxigranos.com,3133401762,2026-03-18,Shopify,332758.80

In [19]:
# # CONSULTAS CUMPLEAÑOS

# query_data = """
# SELECT DISTINCT v.Cliente, 
# 	cc.Nombres + ' ' +  cc.Apellidos AS Nombre, 
# 	cc.Email, cc.Celular, 
# 	v.Fecha AS Fecha_Venta 
# 	,SUM(Venta_Neta) AS Venta, 
# 	Canal
# FROM Ventas_Comerssia.dbo.Ventas_Unificadas v
# INNER JOIN Ventas_Comerssia.dbo.View_Contacto_Clientes cc ON cc.Cliente = v.Cliente
# WHERE Codigo_Descuento LIKE '%Cump%'
# 	AND Fecha BETWEEN '2025-07-04' AND '2025-07-31'
# 	AND NOT EXISTS (SELECT 1 FROM COMERSSIA.PROVENZAL.dbo.EmpleadosProvenzal e WHERE e.Codigo = v.cliente ) 
# GROUP BY  v.Cliente,
#        cc.Nombres + ' ' +  cc.Apellidos,
#        cc.Email,
#        cc.Celular,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# df_ventas = pd.read_sql(query_data, engine)
# df_ventas.head()

In [20]:
# Leer archivo
df_revie = pd.read_excel("Atribucion.xlsx")

# Seleccionar columnas relevantes
df_campania = df_revie[['Email', 'First Name', 'Last Name', 'Phone', 'Company']].copy()

# 4. Normalizar correos
df_campania['Email'] = df_campania['Email'].str.lower().str.strip()

In [21]:
# Normalizar df_ventas
df_ventas['Email'] = df_ventas['Email'].str.lower().str.strip()
df_ventas['Fecha_Venta'] = pd.to_datetime(df_ventas['Fecha_Venta']).dt.date

# Merge por email
df_atribucion = pd.merge(df_ventas, df_campania, on='Email', how='inner')

# Sumar la venta total atribuida
total_venta = df_atribucion['Venta'].sum()

filas = len(df_atribucion) # Ver cuántas filas hay realmente

print(f"Total de Ventas: {filas}")
print(f"Total de venta atribuida: {total_venta:,.2f}"  )
# Resultado final
df_atribucion.head()

Total de Ventas: 5
Total de venta atribuida: 1,900,024.86

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,First Name,Last Name,Phone,Company
0,97157,C30238208,NATALIA RODAS,natalia_rodas_lopez@hotmail.com,3174375003,2026-03-18,Shopify,254610.90,NATALIA,RODAS,3174375003,9266151
1,97174,C77146998,WALID WALID,osmansamar@hotmail.com,3165254677,2026-03-19,Shopify,690314.40,WALID,WALID,3156679499,1065858393
2,97212,C32242035,JESSICA MORA,jessimora@hotmail.com,3164465064,2026-03-21,Shopify,317633.40,JESSICA,MORA,3164465064,32242035
3,97213,C32242035,JESSICA MORA,jessimora@hotmail.com,3164465064,2026-03-21,Shopify,433594.80,JESSICA,MORA,3164465064,32242035
4,97239,C900518285,MARIA CAROLINA SANZ IZQUIERDO,carolinasanzi@gmail.com,3203030753,2026-03-23,Shopify,203871.36,MARIA CAROLINA,SANZ IZQUIERDO,3203030753,52415509

In [22]:
df_atribucion.to_excel('Ventas.xlsx', index=False)