In [326]:
import pandas as pd
from sqlalchemy import create_engine
import urllib

In [327]:
params_data = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=181.57.189.150,1433;"
    "DATABASE=Ventas_Shopify;"
    "UID=sa;"
    "PWD=P@ssw0rd*;"
)

# Crear el motor de conexión
engine_data = create_engine(f"mssql+pyodbc:///?odbc_connect={params_data}")

# Configurar cadena de conexión
params_com = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=comerssiamirror.eastus2.cloudapp.azure.com,38693;"
    "DATABASE=PROVENZAL;"
    "UID=provenzal;"
    "PWD=PE@4:BRy/<1VWkp;"
)

# Crear el motor
engine_com = create_engine(f"mssql+pyodbc:///?odbc_connect={params_com}")

In [328]:
# query_data = """
# SELECT DISTINCT c.Id AS Cliente,
#        c.Nombre,
#        c.Email AS Email,
#        c.Telefono AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(v.Valor_Neto) AS Venta
# FROM Contacto_Clientes c
# INNER JOIN Ventas_ShopifyMoviNova v ON c.id = v.id_cliente
# WHERE v.fecha >= '2025-07-10'
#     AND v.Fecha <= '2025-07-15'
# GROUP BY c.Id,
#        c.Nombre,
#        c.Email,
#        c.Telefono,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_shopify = pd.read_sql(query_data, engine_data)

# query_com = """
# SELECT DISTINCT c.CLICodigo AS Cliente,
#        c.CLINombres + ' ' + c.CLIApellidos AS Nombre,
#        c.CLIEmailPrincipal AS Email,
#        c.CLICelular AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(v.Venta_Neta) AS Venta
# FROM Contacto_Clientes c
# INNER JOIN Ventas_MoviNova v ON c.CLICodigo = v.Cliente
# WHERE v.fecha >= '2025-07-10'
#     AND v.Fecha <= '2025-07-15'
# GROUP BY  c.CLICodigo,
#        c.CLINombres + ' ' + c.CLIApellidos,
#        c.CLIEmailPrincipal,
#        c.CLICelular,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_comerssia = pd.read_sql(query_com, engine_com)

# ventas_total = pd.concat([ventas_comerssia, ventas_shopify], ignore_index=True)
# ventas_total.head()

In [329]:
# #consulta segmentada 
# query_data = """
# SELECT DISTINCT c.Id AS Cliente,
#        c.Nombre,
#        c.Email AS Email,
#        c.Telefono AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(v.Valor_Neto) AS Venta
# FROM Contacto_Clientes c
# INNER JOIN Ventas_ShopifyMoviNova v ON c.id = v.id_cliente
# INNER JOIN ItemsVentas_ShopifyMovinova iv ON v.Pedido = iv.Id_Pedido
# INNER JOIN Homologos h ON iv.SKU_Item = h.SKU_Actual
# WHERE v.fecha >= '2025-07-10'
#     AND v.Fecha <= '2025-07-15'
#     AND h.categoria = 'CUIDADO FACIAL'
# GROUP BY c.Id,
#        c.Nombre,
#        c.Email,
#        c.Telefono,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_shopify = pd.read_sql(query_data, engine_data)

query_com = """
SELECT DISTINCT c.CLICodigo AS Cliente,
       c.CLINombres + ' ' + c.CLIApellidos AS Nombre,
       c.CLIEmailPrincipal AS Email,
       c.CLICelular AS Celular,
       v.Fecha AS Fecha_Venta,
       v.Canal,
       SUM(v.Venta_Neta) AS Venta
FROM Contacto_Clientes c
INNER JOIN Ventas_MoviNova v ON c.CLICodigo = v.Cliente
WHERE v.fecha >= '2025-07-10'
    AND v.Fecha <= '2025-07-15'
    AND Categoria = 5
GROUP BY  c.CLICodigo,
       c.CLINombres + ' ' + c.CLIApellidos,
       c.CLIEmailPrincipal,
       c.CLICelular,
       v.Fecha,
       v.Canal
"""

# Ejecutar y cargar en DataFrame
ventas_comerssia = pd.read_sql(query_com, engine_com)
ventas_total = ventas_comerssia
# ventas_total = pd.concat([ventas_comerssia, ventas_shopify], ignore_index=True)
ventas_total.head()

,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,C0601620024,SONIA FRANCIA TORRES,sofra1019@gmil.com,1111111111,2025-07-10,Retail,50420.17
1,C1000613230,ANDRES CASALLAS,andresfcasallasb@gmail.com,3103414671,2025-07-14,Retail,138655.46
2,C1003720833,ANDREA DURANGO,andreadurangol@outlook.com,3043791159,2025-07-10,Retail,74789.92
3,C1013678709,OSCAR JAVIER MATALLANA CASTELLANOS,negado@provenzal.com.co,3213357678,2025-07-15,Retail,74789.92
4,C1017207202,DANIELA RODRIGUEZ BRAND,negado@provenzal.net,3112534600,2025-07-10,Retail,50420.17

In [330]:
#CONSULTAS CUMPLEAÑOS

# query_data = """
# SELECT DISTINCT c.Id AS Cliente,
#        c.Nombre,
#        c.Email AS Email,
#        c.Telefono AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(v.Valor_Neto) AS Venta
# FROM Contacto_Clientes c
# INNER JOIN Ventas_ShopifyMoviNova v ON c.id = v.id_cliente
# WHERE v.fecha >= '2025-06-06'
#     AND v.Fecha <= '2025-06-30'
#     AND v.Codigo_Descuento LIKE '%CUMP%'
# GROUP BY c.Id,
#        c.Nombre,
#        c.Email,
#        c.Telefono,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_shopify = pd.read_sql(query_data, engine_data)

# query_com = """
# SELECT DISTINCT c.CLICodigo AS Cliente,
#        c.CLINombres + ' ' + c.CLIApellidos AS Nombre,
#        c.CLIEmailPrincipal AS Email,
#        c.CLICelular AS Celular,
#        v.Fecha AS Fecha_Venta,
#        v.Canal,
#        SUM(v.Venta_Neta) AS Venta
# FROM Contacto_Clientes c
# INNER JOIN Ventas_MoviNova v ON c.CLICodigo = v.Cliente
# WHERE v.Fecha >= '2025-06-06'
#     AND v.Fecha <= '2025-06-30'
#     AND v.ICPDescripcion LIKE '%CUMP%'
# GROUP BY  c.CLICodigo,
#        c.CLINombres + ' ' + c.CLIApellidos,
#        c.CLIEmailPrincipal,
#        c.CLICelular,
#        v.Fecha,
#        v.Canal
# """

# # Ejecutar y cargar en DataFrame
# ventas_comerssia = pd.read_sql(query_com, engine_com)

# ventas_total = pd.concat([ventas_comerssia, ventas_shopify], ignore_index=True)
# ventas_total.head()

In [331]:
# Cargar el archivo Excel
df_raw = pd.read_excel("Atribucion.xlsx" )

# Seleccionar columnas relevantes
df_campania = df_raw[['email', 'campaignName', 'sentAt', 'openedAt', 'clicks']].copy()

# Renombrar columnas
df_campania.rename(columns={
    'email': 'Email',
    'campaignName': 'campania',
    'sentAt': 'fecha_envio',
    'openedAt': 'apertura',
    'clicks': 'clics'
}, inplace=True)

# Convertir fecha de envío a formato datetime
df_campania['fecha_envio'] = pd.to_datetime(df_campania['fecha_envio'])

# Extraer primera fecha de apertura (si viene como lista en string)
df_campania['apertura'] = df_campania['apertura'].apply(
    lambda x: eval(x)[0] if isinstance(x, str) and x.startswith('[') and len(eval(x)) > 0 else None
)
df_campania['apertura'] = pd.to_datetime(df_campania['apertura'], errors='coerce').dt.tz_localize(None)
df_campania['fecha_envio'] = pd.to_datetime(df_campania['fecha_envio'], errors='coerce').dt.tz_localize(None)

# Detectar si hubo clics (true si hay al menos un clic registrado en la lista)
def tiene_click(x):
    if isinstance(x, str) and x.startswith('['):
        try:
            return len(eval(x)) > 0
        except:
            return False
    return False

df_campania['clic'] = df_campania['clics'].apply(tiene_click)

# Dejar solo columnas clave para análisis
df_campania = df_campania[['Email', 'campania', 'fecha_envio', 'apertura', 'clic']]

In [332]:
# Filtrar solo clientes que abrieron el correo 

df_abiertos = df_campania[df_campania['apertura'].notnull()].copy()

fecha_maxima = pd.to_datetime('2025-07-16')
df_abiertos_filtrados = df_abiertos[df_abiertos['apertura'] <= fecha_maxima]

df_abiertos_filtrados = df_abiertos_filtrados.drop_duplicates(subset='Email', keep='first')

total_abiertos = df_abiertos_filtrados['Email'].nunique()
print(f"Número de clientes que abrieron hasta {fecha_maxima.date()}: {total_abiertos}")

# Muestra una muestra
df_abiertos_filtrados.tail()

Número de clientes que abrieron hasta 2025-07-16: 2537

,Email,campania,fecha_envio,apertura,clic
15306,elena_33@hotmail.com,Escalonado Facial 2,NaT,2025-07-15 00:19:47,False
15307,juliremolina@yahoo.com,Escalonado Facial 2,NaT,2025-07-15 19:12:15,False
15308,gpcastanoh@gmail.com,Escalonado Facial 2,NaT,2025-07-15 21:39:51,False
15310,margara312@msn.com,Escalonado Facial 2,NaT,2025-07-15 03:49:05,False
15311,cgabogados1@gmail.com,Escalonado Facial 2,NaT,2025-07-15 16:49:59,False

In [333]:
df_abiertos_filtrados['Email'] = df_abiertos['Email'].str.lower()
ventas_total['Email'] = ventas_total['Email'].str.lower()

# Merge entre ventas y campañas abiertas
df_atribucion = pd.merge(
    ventas_total,
    df_abiertos_filtrados[['Email', 'campania', 'fecha_envio']],
    on='Email',
    how='inner'
)

df_atribucion = df_atribucion.drop_duplicates(subset='Email', keep='first')
filas = len(df_atribucion) # Ver cuántas filas hay realmente

print(f"Total de filas: {filas}")
df_atribucion.head()

Total de filas: 30

,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,campania,fecha_envio
0,C1125228495,LINA MARCELA CAICEDO VANEGAS,linacaicedo1@gmail.com,3207949129,2025-07-11,Retail,87857.14,Escalonado Facial 2,2025-07-10 16:10:02
1,C24344429,KAIRA PAOLA CORDOBA BEJARANO,kaco_823@hotmail.com,3104748012,2025-07-11,Retail,87857.14,Escalonado Facial 2,NaT
2,C32529764,MARTA PIEDAD ECHEVERRI,canelamaria24@gmail.com,3160495355,2025-07-14,Retail,540504.20,Escalonado Facial 2,NaT
3,C43183786,ALICIA QUIROGA ECHEVERRI,aliciaqx@yahoo.com,3146619248,2025-07-15,Chat Center,248571.43,Escalonado Facial 2,2025-07-10 16:09:55
4,C43525640,PATRICIA PEREZ,patricia_perezc@hotmail.com,3012155058,2025-07-15,Retail,50420.17,Escalonado Facial 2,NaT

In [334]:
# Sumar el total de ventas atribuidas
total_venta = df_atribucion['Venta'].sum()

print(f"Total de venta atribuida: {total_venta:,.0f}")

Total de venta atribuida: 7,922,090

In [335]:
# # Merge entre ventas y campañas abiertas
# df_atribucion = pd.merge(
#     ventas_total,
#     df_abiertos[['Email', 'campania', 'fecha_envio','apertura','clic']],
#     on='Email',
#     how='inner'
# )

# # Días posteriores al envío
# df_atribucion['dias_post_envio'] = (df_atribucion['fecha_venta'] - df_atribucion['fecha_envio']).dt.days

# # Filtramos ventas hechas dentro de los 5 días después del envío
# df_atribucion_filtrada = df_atribucion[
#     (df_atribucion['dias_post_envio'] >= 0) & (df_atribucion['dias_post_envio'] <= 5)
# ].copy()

# # Mostramos resultados
# df_atribucion_filtrada.head()