In [159]:
import pandas as pd
from sqlalchemy import create_engine
import urllib
import ast
from datetime import timedelta
import os
from dotenv import load_dotenv

load_dotenv()

True

In [160]:
params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={os.getenv('DB_SERVER')};"
    "DATABASE=Ventas_Comerssia;"
    f"UID={os.getenv('DB_USER')};"
    f"PWD={os.getenv('DB_PASSWORD')};"
)


# Crear el motor de conexión
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [161]:
query = """
SELECT DISTINCT v.Pedido,
    v.Cliente,
    c.Nombres + ' ' + c.Apellidos AS Nombre,
    c.Email AS Email,
    c.Celular AS Celular,
    v.Fecha AS Fecha_Venta,
    v.Canal,
    SUM(v.Venta_Neta) AS Venta
FROM Ventas_Comerssia.dbo.Contacto_Clientes c
INNER JOIN Ventas_Comerssia.dbo.Ventas_Unificadas v ON c.Cliente = v.Cliente
WHERE v.fecha >= '2026-05-5'
    AND v.Fecha <= '2026-05-10'
    AND (Canal = 'Shopify' OR Ubicacion = 'Social Selling')
    AND v.Venta_Neta > 0
GROUP BY  v.Pedido,
    v.Cliente,
    c.Nombres + ' ' + c.Apellidos,
    c.Email,
    c.Celular,
    v.Fecha,
    v.Canal
"""

# Ejecutar y cargar en DataFrame
df_ventas = pd.read_sql(query, engine)
df_ventas.head()

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,4354369417,C427700,JORDAN SCHLIPKEN,j.schlipken@aruba.com,3183753407,2026-05-05,Chat Center,642857.13
1,4354369482,C800185150,None,milena.correa@sony.com,3102691387,2026-05-05,Chat Center,957983.16
2,4354369705,C52853176,MARIBEL DIAZ BENITO,maribeldiazbenito@gmail.com,3107724479,2026-05-05,Chat Center,273949.58
3,4354369800,C32702903,FEORELLA SCHEMBRI RIOS,fpschembri@hotmail.com,3173639552,2026-05-05,Chat Center,569117.64
4,4354370162,C1026268896,MANUEL HERRERA,manurherrera234@gmail.com,3175106805,2026-05-06,Chat Center,507142.85

In [162]:
# # CONSULTAS CUMPLEAÑOS

# query_data = """
# SELECT DISTINCT v.Pedido,
# 	v.Cliente, 
# 	cc.Nombres + ' ' +  cc.Apellidos AS Nombre, 
# 	cc.Email, cc.Celular, 
# 	v.Fecha AS Fecha_Venta,
#     Canal,
#     SUM(Venta_Neta) AS Venta
# FROM Ventas_Comerssia.dbo.Ventas_Unificadas v
# INNER JOIN Ventas_Comerssia.dbo.Contacto_Clientes cc ON cc.Cliente = v.Cliente
# WHERE (Codigo_Descuento = '0001 Cumpleaños Cliente 25%' or Codigo_Descuento = 'MAYO_2026')
# 	AND Fecha BETWEEN '2026-05-6' AND '2026-05-11'
# GROUP BY  v.Pedido,
# 	v.Cliente,
#     cc.Nombres + ' ' +  cc.Apellidos,
#     cc.Email,
#     cc.Celular,
#     v.Fecha,
#     v.Canal
# """


# # Ejecutar y cargar en DataFrame
# df_ventas = pd.read_sql(query_data, engine)
# df_ventas.head()

In [163]:
# Leer archivo
df_indigitall = pd.read_excel("Atribucion.xlsx")

# Seleccionar columnas relevantes
df_campania = df_indigitall[['phone', 'campaignName', 'sentAt',  'clicks']].copy()

# Renombrar columnas
df_campania.rename(columns={
    'phone': 'Celular',
    'campaignName': 'campania',
    'sentAt': 'fecha_envio',
    'clicks': 'clics'
}, inplace=True)

# Extraer primera fecha de apertura (si viene como lista en string)
df_campania['clics'] = df_campania['clics'].apply(
    lambda x: eval(x)[0] if isinstance(x, str) and x.startswith('[') and len(eval(x)) > 0 else None
)
df_campania['clics'] = pd.to_datetime(df_campania['clics'], errors='coerce').dt.tz_localize(None)
df_campania['fecha_envio'] = pd.to_datetime(df_campania['fecha_envio'], errors='coerce').dt.tz_localize(None).dt.date

df_enviados = df_campania[df_campania['fecha_envio'].notnull()].copy()
df_clics =  df_campania[df_campania['clics'].notnull()].copy()

fecha_maxima = pd.to_datetime('2026-05-10').date()
df_clics_filtrados = df_clics[df_clics['clics'].dt.date <= fecha_maxima]

df_clics_filtrados = df_clics_filtrados.drop_duplicates(subset='Celular', keep='first')

total_clics = df_clics_filtrados['Celular'].nunique()

In [164]:
# df_enviados['Celular'] = df_enviados['Celular'].astype(str)
# df_ventas['Fecha_Venta'] = pd.to_datetime(df_ventas['Fecha_Venta']).dt.date

# # Merge por email
# df_merge = pd.merge(df_ventas, df_enviados, on='Celular', how='inner')

# df_merge

In [165]:
df_enviados['Celular'] = df_enviados['Celular'].astype(str)
df_ventas['Fecha_Venta'] = pd.to_datetime(df_ventas['Fecha_Venta']).dt.date

# Merge por email
df_merge = pd.merge(df_ventas, df_enviados, on='Celular', how='inner')

# Filtrar ventas dentro de 5 días desde la fecha de envio
df_merge['dias_post_apertura'] = (df_merge['Fecha_Venta'] - df_merge['fecha_envio']).apply(lambda x: x.days)
df_atribucion = df_merge[
    (df_merge['dias_post_apertura'] >= 0) &
    (df_merge['dias_post_apertura'] <= 5)
]

# Sumar la venta total atribuida
tottal_venta = df_atribucion['Venta'].sum()

filas = len(df_atribucion) # Ver cuántas filas hay realmente

print(f"Número de clientes que hicieron clic hasta {fecha_maxima}: {total_clics}")
print(f"Clientes Efectivos: {filas}")
print(f"Total de venta atribuida: {tottal_venta:,.2f}")
# Resultado final
df_atribucion.head()

Número de clientes que hicieron clic hasta 2026-05-10: 30
Clientes Efectivos: 17
Total de venta atribuida: 4,509,702.59

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,campania,fecha_envio,clics,dias_post_apertura
0,4354374130,C43513908,LINA LONDOÑO,linamarialon16@gmail.com,3104695145,2026-05-07,Chat Center,63025.21,ENVIO GRATIS 4 - 14 MAYO,2026-05-05,2026-05-05 23:28:52,2
1,4354376062,C49760764,DIOSELINA NEGRETE VILLAFAÑE,dinevi70@yahoo.com,3112514384,2026-05-08,Chat Center,231092.43,ENVIO GRATIS 4 - 14 MAYO,2026-05-05,2026-05-05 23:25:25,3
2,4354378002,C80758573,JULIAN EDUARDO MENDOZA ROJAS,juli_men83@hotmail.com,3102540728,2026-05-09,Chat Center,66386.55,ENVIO GRATIS 4 - 14 MAYO,2026-05-05,NaT,4
3,4354378147,C39031907,ROSILIA CONRADO,rosicon23@gmail.com,3017716111,2026-05-09,Chat Center,164705.88,ENVIO GRATIS 4 - 14 MAYO,2026-05-05,NaT,4
4,98961,C1234089727,DAVID ORTEGA,davidortega612@gmail.com,3154484070,2026-05-05,Shopify,57980.70,ENVIO GRATIS 4 - 14 MAYO,2026-05-05,NaT,0

In [166]:
df_atribucion.to_excel('Ventas.xlsx', index=False)