In [43]:
import pandas as pd
from sqlalchemy import create_engine
import urllib
import ast
from datetime import timedelta
import os
from dotenv import load_dotenv

load_dotenv()

True

In [44]:
params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={os.getenv('DB_SERVER')};"
    "DATABASE=Ventas_Comerssia;"
    f"UID={os.getenv('DB_USER')};"
    f"PWD={os.getenv('DB_PASSWORD')};"
)


# Crear el motor de conexión
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [45]:
query_com = """
SELECT DISTINCT Pedido,
    c.Cliente,
    c.Nombres + ' ' + c.Apellidos AS Nombre,
    c.Email AS Email,
    c.Celular AS Celular,
    v.Fecha AS Fecha_Venta,
    v.Canal,
    SUM(v.Venta_Neta) AS Venta
FROM Ventas_Comerssia.dbo.Contacto_Clientes c
INNER JOIN Ventas_Comerssia.dbo.Ventas_Unificadas v ON c.Cliente = v.Cliente
WHERE v.fecha >= '2026-05-6'
    AND v.Fecha <= '2026-05-11'
    AND Canal IN ('Shopify')
    AND v.Venta_Neta > 0
GROUP BY  Pedido,
    c.Cliente,
    c.Documento,
    c.Nombres + ' ' + c.Apellidos,
    c.Email,
    c.Celular,
    v.Fecha,
    v.Canal
"""

# Ejecutar y cargar en DataFrame
df_ventas = pd.read_sql(query_com, engine)

df_ventas.head()

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta
0,99014,C52690180,MAURICIO CELY,natacely@hotmail.com,3153374445,2026-05-06,Shopify,283181.1
1,99015,C52809195,MARA TOVAR CURIEUX,maratovar@gmail.com,3002085196,2026-05-06,Shopify,134448.0
2,99016,C60401947,MARTHA ROJAS,julian.espinosarojas@gmail.com,3132855064,2026-05-06,Shopify,226881.0
3,99017,C1090447230,ANDREA PEREZ,anlopeni0304@hotmail.com,3103728539,2026-05-06,Shopify,214276.5
4,99018,C7720151,EDUAR ANDRES FERNÁNDEZ PEREZ,e.andres2420@gmail.com,3189694351,2026-05-06,Shopify,297466.2

In [46]:
# # CONSULTAS CUMPLEAÑOS

# query_data = """
# SELECT DISTINCT Pedido,
#     v.Cliente, 
# 	cc.Nombres + ' ' +  cc.Apellidos AS Nombre, 
# 	cc.Email, cc.Celular, 
# 	v.Fecha AS Fecha_Venta,
# 	Canal,
#     SUM(Venta_Neta) AS Venta 
# FROM Ventas_Comerssia.dbo.Ventas_Unificadas v
# INNER JOIN Ventas_Comerssia.dbo.Contacto_Clientes cc ON cc.Cliente = v.Cliente
# WHERE (Codigo_Descuento = '0001 Cumpleaños Cliente 25%' or Codigo_Descuento = 'MAYO_2026')
# 	AND Fecha BETWEEN '2026-05-19' AND '2026-05-24'
#     AND Canal = 'Shopify'
# GROUP BY  Pedido,
#     v.Cliente,
#     cc.Nombres + ' ' +  cc.Apellidos,
#     cc.Email,
#     cc.Celular,
#     v.Fecha,
#     v.Canal
# """


# # Ejecutar y cargar en DataFrame
# df_ventas = pd.read_sql(query_data, engine)
# df_ventas.head()

In [47]:
# Leer archivo
df_revie = pd.read_excel("Atribucion.xlsx")

# Seleccionar columnas relevantes
df_campania = df_revie[['Email', 'First Name', 'Last Name', 'Phone', 'Company']].copy()

# 4. Normalizar correos
df_campania['Email'] = df_campania['Email'].str.lower().str.strip()

In [48]:
# Normalizar df_ventas
df_ventas['Email'] = df_ventas['Email'].str.lower().str.strip()
df_ventas['Fecha_Venta'] = pd.to_datetime(df_ventas['Fecha_Venta']).dt.date

# Merge por email
df_atribucion = pd.merge(df_ventas, df_campania, on='Email', how='inner')

# Sumar la venta total atribuida
total_venta = df_atribucion['Venta'].sum()

filas = len(df_atribucion) # Ver cuántas filas hay realmente

print(f"Total de Ventas: {filas}")
print(f"Total de venta atribuida: {total_venta:,.2f}"  )
# Resultado final
df_atribucion.head()

Total de Ventas: 23
Total de venta atribuida: 5,927,140.09

,Pedido,Cliente,Nombre,Email,Celular,Fecha_Venta,Canal,Venta,First Name,Last Name,Phone,Company
0,99022,C26671310,ALEJANDRA RESTREPO,amarestrepob@gmail.com,3017542738,2026-05-06,Shopify,328557.30,ALEJANDRA,RESTREPO,3045407337,26671310
1,99027,C14800293,CARLOS ARTURO ESCOBAR BOTERO,carlosmons@hotmail.com,3186155123,2026-05-06,Shopify,523506.90,CARLOS ARTURO,ESCOBAR BOTERO,3186155123,14800293
2,99031,C1047420451,DANIELA PULLO,dani_puello@hotmail.com,3016818878,2026-05-06,Shopify,163228.28,DANIELA,PULLO,3016818878,1047420451
3,99039,C31154101,ANA MILENA DIAZ GIRALDO,anamilenadiazg@gmail.com,3176406262,2026-05-06,Shopify,499768.43,ANA MILENA,DIAZ GIRALDO,3176406262,31154101
4,99049,C22222222222,CONSUMIDOR FINAL,catag17@gmail.com,3243859073,2026-05-06,Shopify,305869.20,CONSUMIDOR,FINAL,3243859073,22222222222

In [49]:
df_atribucion.to_excel('Ventas.xlsx', index=False)